spring:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration-time: ${JWT_TIME}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email, openid
            client-name: Google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            client-name: GitHub
        provider:
          google:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  jackson:
    time-zone: America/Lima
  datasource:
    # Use Railway's provided environment variables for robustness
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # --- ADD THESE HIKARI SETTINGS ---
    hikari:
      connection-timeout: 30000 # Wait 30 seconds for a connection
      initialization-fail-timeout: 60000 # Wait 60 seconds for the pool to initialize
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#redirect-uri-base: ${REDIRECT_URI_BASE}
app:
  redirect:
    uri:
      app: ${URI_APP}

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG

# JSF and PrimeFaces configuration
jakarta:
  faces:
    PROJECT_STAGE: Development

# primefaces.THEME=saga
# primefaces.FONT_AWESOME=true
joinfaces:
  faces-servlet:
    url-mappings:
      - "*.xhtml"
      - "/"
